version: "3.7"
services:
  gateway:
    image: webthingsio/gateway
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/.webthings/addons/tellstick-adapter

  telldus:
    build:
      context: ./docker
    restart: always
    privileged: true
    ports:
      - 50800:50800
    volumes:
      - ./tellstick.conf:/etc/tellstick.conf
